### ISSUE TITLE
license

### ISSUE THREAD

**Issue by sdhoward** [blazer82/baremetal-blinky.teensy#1]
Great project! I see the following credit for the `teensy/` directory:

> Linker files and startup code are based on the Teensy Core Libraries for Arduino by Paul Stoffregen.

What about the code that you wrote (`src/` and `include/`), is that distributed under an open source license? If so, would you add one to the repo?

**Comment by blazer82** [comment]
Thanks for bringing this up. I added a license file - the code is open source using the MIT license.

Since the Teensy Core Libraries don't seem to have a license I can only credit them in the readme and hope MIT is okay.
